MAX_AUTHENTICITY_RETRIES = 2

BANNED_PHRASES = [
    # Openers / transitions
    "in today's fast-paced world",
    "in today's digital world",
    "in today's world",
    "in the modern world",
    "in this day and age",
    "have you ever wondered",
    "let's be honest",
    "let's face it",
    "the truth is",
    "the fact is",
    "it's no secret that",
    "it goes without saying",
    "needless to say",
    "at the end of the day",
    "when it comes to",
    "in the realm of",
    "in the world of",
    "in the landscape of",
    "in the ever-evolving world",
    "in the ever-changing landscape",
    # Hype / cliché
    "game-changer",
    "game changing",
    "change the game",
    "unlock the power of",
    "unlock the potential",
    "unlock new opportunities",
    "revolutionize",
    "revolutionary",
    "paradigm shift",
    "transformative",
    "cutting-edge",
    "state-of-the-art",
    "bleeding edge",
    "seamlessly integrate",
    "seamless integration",
    "seamless experience",
    "robust solution",
    "robust platform",
    "synergy",
    "synergize",
    "circle back",
    "deep dive",
    "deep-dive",
    "drill down",
    "takeaway",
    "key takeaway",
    # LinkedIn guru
    "let's dive in",
    "let's dive into",
    "diving into",
    "delve into",
    "delve deeper",
    "navigate the",
    "navigate this",
    "navigate the complex",
    "thought leadership",
    "thought leader",
    "think outside the box",
    "blue-sky thinking",
    "move the needle",
    "one thing I've learned",
    "lessons learned",
    "here are my thoughts",
    "I wanted to share",
    "I wanted to take a moment",
    "I'm excited to announce",
    "I'm thrilled to share",
    "proud to announce",
    "humbled to share",
    # Generic abstractions
    "the power of",
    "the importance of",
    "the future of",
    "the beauty of",
    "the magic of",
    "in a nutshell",
    "long story short",
    "at scale",
    "in the corporate world",
    "in business",
    "actionable insights",
    "actionable strategies",
    "best-in-class",
    "world-class",
    "industry-leading",
    "proven track record",
    "results-driven",
    "data-driven",
    " ROI",
    "pain points",
    "touch base",
    "reach out",
    "quick question",
    # Overused AI content
    "AI-powered",
    "AI-driven",
    "AI-enabled",
    "leveraging AI",
    "harness the power of AI",
    "the power of artificial intelligence",
    "in the age of AI",
    "the AI revolution",
    "embrace AI",
    "future-proof",
    "digital transformation",
]
